version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3333:3333"
    depends_on:
      - redis

  redis:
    image: "redis:alpine"
    container_name: "redis"
    ports:
      - "6379:6379"